# Generated by Django 5.2 on 2025-09-30 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, unique=True)),
                ("floor", models.PositiveIntegerField()),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["floor", "number"],
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_type", models.CharField(max_length=20)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("billing_period_end", models.DateField()),
                ("status", models.CharField(max_length=20)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="homa.apartment",
                    ),
                ),
            ],
            options={
                "ordering": ["-billing_period_end"],
            },
        ),
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residents",
                        to="homa.apartment",
                    ),
                ),
            ],
            options={
                "ordering": ["apartment__floor", "apartment__number"],
            },
        ),
        migrations.CreateModel(
            name="ElectricityIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_reading", models.PositiveIntegerField()),
                ("current_reading", models.PositiveIntegerField()),
                ("reading_date", models.DateField()),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="electricity_indicators",
                        to="homa.apartment",
                    ),
                ),
            ],
            options={
                "ordering": ["-reading_date"],
                "unique_together": {("apartment", "reading_date")},
            },
        ),
        migrations.CreateModel(
            name="WaterIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_reading", models.PositiveIntegerField()),
                ("current_reading", models.PositiveIntegerField()),
                ("reading_date", models.DateField()),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_indicators",
                        to="homa.apartment",
                    ),
                ),
            ],
            options={
                "ordering": ["-reading_date"],
                "unique_together": {("apartment", "reading_date")},
            },
        ),
    ]
