# Generated by Django 5.2 on 2025-10-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homa", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="status",
        ),
    ]
