# Generated by Django 5.2 on 2025-10-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homa", "0002_remove_bill_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
