# Generated by Django 5.2 on 2025-09-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="contract",
            options={
                "ordering": ["title"],
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["name"],
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["name"],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["employee_id"],
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="O",
                max_length=1,
            ),
        ),
        migrations.AlterModelTable(
            name="company",
            table="company",
        ),
        migrations.AlterModelTable(
            name="contract",
            table="contract",
        ),
        migrations.AlterModelTable(
            name="customer",
            table="customer",
        ),
        migrations.AlterModelTable(
            name="department",
            table="department",
        ),
        migrations.AlterModelTable(
            name="employee",
            table="employee",
        ),
    ]
